Repository scalar-labs/scalar-kubernetes, pull requests merged in 2021-03, with the labels that each got.

#110 Update docs for upgrade terraform to 0.14
  docs/PortForwardingToK8sAPIInScalarTerraformNetwork.md
  docs/PrepareBastionTool.md
Labels: documentation, enhancement

#111 Update DynamoDB support to the helm chart
  charts/stable/schema-loading/Chart.yaml
  charts/stable/schema-loading/README.md
  charts/stable/schema-loading/templates/batchjob-schema-loading.yaml
  charts/stable/schema-loading/values.yaml
  conf/scalardl-custom-values.yaml
  conf/schema-loading-custom-values.yaml
Labels: improvement

#112 Refactoring to use cloud_provider to install awscli role
  docs/PrepareBastionTool.md
  playbooks/playbook-install-tools.yml
Labels: improvement

#113 Fix typo
  playbooks/roles/prometheus/tasks/deploy.yml
Labels: bugfix

#114 Fix broken links in documents
  docs/DeployScalarDLAnsible.md
  docs/GettingStarted.md
  docs/HelmValuesFiles.md
  docs/K8sLogCollectionGuide.md
  docs/K8sMonitorGuide.md
  docs/PortForwardingToK8sAPIInScalarTerraformNetwork.md
Labels: documentation
